-- -----------------------------------------------------------------------------
-- WILAYA
-- -----------------------------------------------------------------------------

INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '01', '01000', 'Adrar');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '02', '02000', 'Chlef');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '03', '03000', 'Laghouat');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '04', '04000', 'Oum El Bouaghi');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '05', '05000', 'Batna');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '06', '06000', 'Béjaïa');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '07', '07000', 'Biskra');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '08', '08000', 'Béchar');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '09', '09000', 'Blida');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '10', '10000', 'Bouira');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '11', '11000', 'Tamanrasset');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '12', '12000', 'Tébessa');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '13', '13000', 'Tlemcen');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '14', '14000', 'Tiaret');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '15', '15000', 'Tizi Ouzou');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '16', '16000', 'Alger');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '17', '17000', 'Djelfa');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '18', '18000', 'Jijel');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '19', '19000', 'Sétif');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '20', '20000', 'Saïda');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '21', '21000', 'Skikda');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '22', '22000', 'Sidi Bel Abbès');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '23', '23000', 'Annaba');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '24', '24000', 'Guelma');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '25', '25000', 'Constantine');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '26', '26000', 'Médéa');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '27', '27000', 'Mostaganem');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '28', '28000', 'M''Sila');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '29', '29000', 'Mascara');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '30', '30000', 'Ouargla');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '31', '31000', 'Oran');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '32', '32000', 'El Bayadh');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '33', '33000', 'Illizi');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '34', '34000', 'Bordj Bou Arreridj');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '35', '35000', 'Boumerdès');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '36', '36000', 'El Tarf');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '37', '37000', 'Tindouf');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '38', '38000', 'Tissemsilt');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '39', '39000', 'El Oued');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '40', '40000', 'Khenchela');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '41', '41000', 'Souk Ahras');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '42', '42000', 'Tipaza');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '43', '43000', 'Mila');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '44', '44000', 'Aïn Defla');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '45', '45000', 'Naâma');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '46', '46000', 'Aïn Témouchent');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '47', '47000', 'Ghardaïa');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '48', '48000', 'Relizane');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '49', '49000', 'Timimoun');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '50', '50000', 'Bordj Badji Mokhtar');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '51', '51000', 'Ouled Djellal');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '52', '52000', 'Béni Abbès');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '53', '53000', 'In Salah');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '54', '54000', 'In Guezzam');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '55', '55000', 'Touggourt');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '56', '56000', 'Djanet');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '57', '57000', 'El Meghaier');
INSERT INTO order_schema.wilaya( code, zip_code, name ) VALUES ( '58', '58000', 'El Menia');

-- -----------------------------------------------------------------------------
-- CITY
-- -----------------------------------------------------------------------------

-- ALGER

INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER CENTRE','16000',36.7727778,3.0588889,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-1ER NOVEMBRE-RP','16001', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-MOURAD-DIDOUCHE','16002', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-BIAR','16003', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-HARRACH','16004', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HUSSEIN-DEY-RP','16005', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KOUBA','16006', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-1ER MAI','16007', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-BAB-EL-OUED','16008', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-EL-ANNASSER','16009', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-FERHAT-BOUSSAD','16010', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-PORT-SAID','16011', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-SIDI-M''HAMED','16012', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BIR-MOURAD-RAIS','16013', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHERAGA-RP','16014', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-MADANIA','16015', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HYDRA','16016', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ROUIBA-RP','16017', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN-BENIAN','16018', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN-TAYA','16019', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-ALI-BASTA','16020', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-EL-KETTANI','16021', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-HAUTE-CASBAH','16022', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-MALIKA-GAID','16023', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BAB-EZZOUAR','16024', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BAB-EZZOUAR-EL-ALIA','16025', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BACHEDJARAH','16026', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BARAKI','16027', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BEN-AKNOUN-RP','16028', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BIRKHADEM','16029', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BOLOGHINE','16030', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ-EL-KIFFAN','16031', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BOUZAREAH','16032', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DAR-EL-BEIDA','16033', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-BIAR-BOUGARA','16034', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-MOURADIA','16035', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA','16036', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-HASSIBA-BEN-BOUALI','16037', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-7 MERVEILLES','16038', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-KHELIFA-BOUKHALFA','16039', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-ROSTOMIA','16040', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-TARIK-IBN-ZIAD','16041', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BAB-EZZOUAR-5 JUILLET','16042', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BEN-AKNOUN-C. MALKI','16043', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BENI-MESSOUS','16044', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BIRTOUTA','16045', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ-EL-BAHRI','16046', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DELY-IBRAHIM','16047', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DJASR-KASENTINA','16048', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DOUERA','16049', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DRARIA','16050', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-HARRACH-H-BADI','16051', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-MOURADIA-AOUDIA','16052', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HAI-EL-BADR','16053', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HAI-EL-FIDA','16054', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KOUBA-EL-ANNASSER','16055', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KOUBA-GARIDI','16056', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('LES EUCALYPTUS','16057', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('MOHAMMADIA','16058', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OUED-SMAR','16059', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RAIS-HAMIDOU','16060', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-MOUSSA','16061', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('STAOUELI','16062', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ZERALDA','16063', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN-NAADJA-HOUARI-BOUMEDIENNE','16064', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN-NADJA','16065', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER FRERES-BELLILI','16066', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER FRERES-SI-BACHIR','16067', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-AHCENE-ASKRI','16068', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-AHCENE-DJANKI','16069', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-ALI-OURAK','16070', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-APN','16071', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-BD DES MARTYRS','16072', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-COUR-SUPREME','16073', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-DIAR-EL-MAHCOUL','16074', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-LES SOURCES','16075', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-MAHIEDDINE','16076', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-PORT','16077', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-SAID-HAMDINE','16078', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-UNIVERSITE-H-BOUMEDIENE','16079', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-ZIANI (police)','16080', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BABA-HASSEN','16081', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BAINS-ROMAINS','16082', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BARAKI-SI-LAKHDAR','16083', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BOUCHAOUI','16084', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CAP-CAXINE','16085', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHERAGA-BANLIEUE','16086', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DERGANA','16087', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DIAR-EL-DJEMAA','16088', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-HAMMADIA','16089', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HAI-EL-DJAMIL','16090', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KHERAICIA','16091', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KOUBA-CITE SEMROUNI','16092', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('MAHELMA','16093', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-FAYET','16094', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SAOULA','16095', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-FREDJ','16096', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SOUIDANIA','16097', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('STAOUELI-CLUB DES PINS','16098', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('TESSALA-EL-MERDJA','16099', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('TIXERAINE','16100', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN-BENIAN-18 FEVRIER','16101', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGERIE-TELECOM','16102', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-PLAGE','16103', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-ACHOUR','16104', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HOPITAL-CENTRAL-ANP','16105', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OUED-ROMANE','16106', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-SIDI-LAKEHEL','16107', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA-PLATEAU','16108', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-YOUCEF','16109', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ZERALDA-BD-SOUIDANI','16110', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BABA-ALI','16111', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-AMARA','16113', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-BRIDJA','16114', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-MARSA','16115', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HERAOUA','16116', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('MAZAFRAN-BOUZEGZA','16117', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-CHEBEL','16118', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-MENDHIL','16119', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('QUARTIER 11 DECEMBRE','16120', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RAHMANIA','16121', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RAMDANIA','16122', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA-DJAAFRI','16123', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-BOUKHRIS','16124', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-HASSEN','16125', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ZAATRIA','16126', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CONSEIL DE LA NATION','16127', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KATIBA EL DJELLOULIA','16128', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('FRERES-ACHOURI','16129', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-AEROPORT-H-BOUMEDIENE','16130', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-BAB-EL-OUED-CHU','16131', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-CHU MUSTAPHA','16132', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HAI BRAHIMI MOHAMED','16133', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HAI NAAMANE LAMRI','16134', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ EL KIFFAN FAIZI','16135', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HUSSEIN-DEY 8 MARS (BROSSETTE)','16136', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI YOUCEF KOUIDRI 389 LOGTS','16137', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL BIAR ALI KHODJA','16138', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BARAKI BD MED BELARBI','16139', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHERARBA 917 LOGTS','16140', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BARAKI 360 LOGTS','16141', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN NAADJA 196 LOGTS','16142', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BENTALHA','16143', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('FRERES-Z''MIRLI','16144', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EUCALYPTUS 500 LOGTS','16145', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BABA ALI ZOUINA','16146', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL MANDHER EL DJAMIL KOUBA','16147', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SEBALA','16148', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SOUIDANIA-HAI-DJAADI','16149', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('HAI-MER ET SOLEIL','16150', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-MOHAMED DOUAR','16151', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-MAKKARIA','16152', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KOUBA-GARIDI 1B','16153', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BAB-EZZOUAR LA CONCORDE','16154', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-BRAHIM-GHARAFA','16155', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-RACHID-KOUACHE','16156', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-ETTHAALIBI','16157', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-BEN-M''HIDI','16158', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-AMARA-RACHID','16159', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI MENIF','16160', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KHARROUBA GARE ROUTIERE','16161', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BOUROUBA','16162', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE KOUBA GARIDI 1','16163', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE BAB EZZOUAR 2','16164', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE BAB EZZOUAR 3','16165', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE BAB EZZOUAR 4','16166', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE BOURAOUI AMAR','16167', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE BAB EZZOUAR 1','16168', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE UNIVERSITAIRE VIEUX KOUBA','16169', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('MINISTERE DES AFFAIRES ETRANGERES','16170', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('STAOUELI-BOUREGAA','16171', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-ASSELAH-HOCINE','16172', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-LA-CONCORDE','16173', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ROUIBA-ENPEI','16174', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-FAYET-AADL-1 530 LOGTS','16175', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHERAGA-C.G.N','16176', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CERCLE MILITAIRE-BENI-MESSOUS','16177', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHERAGA-NORD','16178', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-FAYET-UNIVERSITE','16179', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE-UNIVERSITAIRE-TALEB-ABDERRAHMANE 1','16180', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SEBALA-AADL-1 839 LOGTS','16181', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-BEN-M''BAREK-ABDELKADER','16182', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA-G.I.R','16183', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ZERALDA-SIDI-MENIF','16184', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-FAYET-PLATEAU','16185', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DRARIA-2','16186', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BAB-EZZOUAR 1 -AADL','16187', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DJISR-KACENTINA-AADL','16188', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-MOUSSA-EL-RAIS','16189', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BABA-ALI-1 299 LOGEMENTS','16190', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('FACULTE DES SCIENCES POLITIQUES','16191', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BABA-HASSEN-20 AOUT 1956','16192', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DELY IBRAHIM FACULTE DES SCIENCES ECONOMIQUES UNIVERSITE D''ALGER 03','16193', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BOUROUBA-SRFE','16194', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DERGANA 2','16195', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DAR-EL-BEIDA-ECOLE-DE-POLICE','16196', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER E.P.R.S','16197', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('KOUBA-GROUPEMENT-DE-RESERVE-ET-D''INTERVENTION (G-R-I)','16198', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ-EL-KIFFAN-LIDO','16199', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BACHEDJARAH-GROUPEMENT-DE-PROTECTION-ET-DE-SECURITE-DE-LA-POLICE','16200', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-ABDELLAH-AADL','16201', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-ABDELLAH-1067-LOGEMENTS','16202', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SAID-HAMDINE-FACULTE-DE-DROIT','16203', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BACHEDJARAH-AADL','16204', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-MARSA-ECOLE-DE-COMMANDEMENT-ET-D''ETAT-MAJOR','16205', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BEN-AKNOUN-CONSEIL-D''ETAT','16206', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RESIDENCE-UNIVERSITAIRE-BAB-EZZOUAR 5','16207', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHERAGA-LES-DUNES','16208', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('SIDI-ABDELLAH-CYBER-PARC','16209', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DAR-EL-BEIDA-DIRECTION-DE-LA-POLICE-DES-FRONTIERES','16210', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-HAMIZ','16211', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BIR-KHADEM-MINISTERE-DE-LA-SOLIDARITE-NATIONALE-DE-LA-FAMILLE-ET-DE-LA-CONDITION-DE-LA-FEMME','16212', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-CENTRE-LA-FACULTE-CENTRALE','16213', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ-EL-BAHRI-AIR','16214', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA-ESDAT','16215', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-GARE-MARITIME','16216', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-BIAR-MINISTERE-DE-L''INDUSTRIE-ET-DES-MINES','16217', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('EL-BIAR-MINISTERE-DES-MOUDJAHIDINE','16218', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-SLIMANE','16219', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA-ALI-KHOUDJA','16220', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('REGHAIA-AISSAT-MUSTAPHA','16221', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ-EL-KIFFAN-BENZIANE','16222', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BORDJ-EL-KIFFAN-KAIDI-MOHAMED','16223', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('BARAKI-HOUCH-EL-MIHOUB','16224', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AIN-BENIAN-BELLE-VUE','16225', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('CHAIBIA-3216-LOGEMENTS','16226', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ZERALDA-1000-LOGEMENTS','16227', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-EST-BUREAU-ITINERANT 1','16228', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-CENTRE-ETABLISSEMENT -POSTAL-ITINERANT 1','16229', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('ALGER-OUEST-ETABLISSEMENT -POSTAL-ITINERANT 1','16230', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('DJAMAA-EL-DJAZAIR','16231', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('AEROPORT-D''ALGER','16232', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('RAHMANIA-300-LOGEMENTS','16233', , ,'16');
INSERT INTO order_schema.city( name, zip_code, latitude, longitude, code_wilaya) VALUES ('OULED-BELHADJ','16234', , ,'16');
