name: Check-Pull-Request

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: Manage versions
      - run: docker build -t order:latest .
