name: Deploy-To-Azure

# TODO: Include Release and Prod branches among target branches.
on:
  pull_request:
    types: [closed]
    branches:
      - Dev

jobs:
  deploy-to-azure:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          login-server: orderregistry.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      # TODO: Manage versions.
      - run: docker build -t orderregistry.azurecr.io/order:latest .
      - run: docker push orderregistry.azurecr.io/order:latest
